# Generated by Django 5.2.10 on 2026-01-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('difficulty_min', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría')], default='A1', max_length=2)),
                ('difficulty_max', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría')], default='C2', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría')], max_length=2)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list)),
                ('estimated_time', models.PositiveIntegerField(default=10)),
                ('new_vocab_count', models.PositiveIntegerField(default=20)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['scenario', 'level', 'order'],
                'unique_together': {('scenario', 'level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('goal', 'Goal'), ('domain', 'Domain'), ('skill', 'Skill'), ('work_domain', 'Work Domain'), ('interest', 'Interest')], db_index=True, max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['type', 'value'],
                'unique_together': {('type', 'value')},
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='tags',
            field=models.ManyToManyField(related_name='scenarios', to='scenarios.tag'),
        ),
        migrations.CreateModel(
            name='UserScenarioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('stars_earned', models.PositiveIntegerField(default=0)),
                ('current_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.milestone')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
