# Generated by Django 5.2.7 on 2026-01-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='goals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='interests',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='work_domain',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
