# Generated by Django 5.2.7 on 2026-01-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_learningprofile_cefr_level_learningprofile_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
