# Generated by Django 5.2.10 on 2026-01-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_learningprofile_hobbies_learningprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='timezone',
            field=models.CharField(default='America/Mexico_City', max_length=50),
        ),
    ]
