# Generated by Django 5.2.10 on 2026-01-15 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='definition_en',
            field=models.TextField(blank=True, help_text='Definición en inglés simple (nivel apropiado)'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='definition_es',
            field=models.TextField(blank=True, help_text='Definición/traducción en español'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='morphological_forms',
            field=models.JSONField(blank=True, default=dict, help_text='Formas automáticas de la palabra. Ejemplos:\n        Verbo: {"present": "swim", "past": "swam", "past_participle": "swum", "gerund": "swimming", "third_person": "swims"}\n        Noun: {"singular": "child", "plural": "children"}\n        Adj: {"positive": "happy", "comparative": "happier", "superlative": "happiest"}'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='phonetic',
            field=models.CharField(blank=True, help_text='Notación fonética IPA (ej: /swɪm/)', max_length=100),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='source',
            field=models.CharField(choices=[('oxford', 'Oxford 3000/5000'), ('cambridge', 'Cambridge Vocabulary Profile'), ('manual', 'Agregado manualmente'), ('pattern', 'Generado con Pattern.en')], default='manual', help_text='Origen de los datos de esta palabra', max_length=50),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL del archivo de audio MP3'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Oración de ejemplo en inglés'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_translation',
            field=models.TextField(blank=True, help_text='Traducción de la oración de ejemplo'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='frequency_rank',
            field=models.PositiveIntegerField(default=0, help_text='Ranking de frecuencia (1=más común, 10000=raro). De Oxford/Cambridge.'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='is_active_vocab',
            field=models.BooleanField(default=False, help_text='¿Palabra objetivo activo (producción) vs pasivo (comprensión)?'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='lemma',
            field=models.CharField(db_index=True, help_text='Forma base/diccionario (ej: swim)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, help_text='Nivel CEFR de dificultad', max_length=2),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(blank=True, help_text='Tipo gramatical: verb, noun, adjective, adverb, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='LEGACY: Usar phonetic en su lugar', max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='translation',
            field=models.CharField(blank=True, help_text='LEGACY: Usar definition_es en su lugar', max_length=200),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(help_text='Palabra exacta (ej: swimming, swam, swims)', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['lemma', 'level'], name='content_voc_lemma_91bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['part_of_speech', 'level'], name='content_voc_part_of_035e54_idx'),
        ),
    ]
