# Generated by Django 5.2.10 on 2026-01-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('vocabulary', '0002_improve_vocabulary_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyInMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_usage', models.TextField(blank=True, help_text='Cómo se usa en este milestone específico. Ej: "Can I have a coffee?"')),
                ('importance_weight', models.IntegerField(choices=[(1, 'Opcional'), (2, 'Útil'), (3, 'Importante'), (4, 'Muy importante'), (5, 'Crítico')], default=3, help_text='Importancia de esta palabra en este milestone')),
                ('is_active_target', models.BooleanField(default=False, help_text='True=Usuario debe poder DECIR esta palabra. False=Solo reconocerla.')),
                ('introduction_order', models.PositiveIntegerField(default=1, help_text='Orden en que se introduce en este milestone (1=primero, 2=segundo, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(help_text='Milestone donde se usa esta palabra', on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='scenarios.milestone')),
                ('vocabulary', models.ForeignKey(help_text='Palabra del diccionario universal', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_usages', to='vocabulary.vocabulary')),
            ],
            options={
                'verbose_name': 'Vocabulary in Milestone',
                'verbose_name_plural': 'Vocabulary in Milestones',
                'db_table': 'vocabulary_in_milestone',
                'ordering': ['introduction_order'],
                'indexes': [models.Index(fields=['milestone', 'importance_weight'], name='vocabulary__milesto_b5fa5f_idx'), models.Index(fields=['milestone', 'introduction_order'], name='vocabulary__milesto_37f51d_idx')],
                'unique_together': {('vocabulary', 'milestone')},
            },
        ),
    ]
