# Generated by Django 5.2.7 on 2026-01-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_ids', models.JSONField(default=list)),
                ('total_available', models.IntegerField(default=0)),
                ('user_level', models.CharField(max_length=10)),
                ('user_goals', models.JSONField(default=dict)),
                ('user_interests', models.JSONField(default=dict)),
                ('filters_applied', models.JSONField(default=list)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'verbose_name_plural': 'Recommendation Logs',
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
