# Generated by Django 5.2.7 on 2026-01-14 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_userrecommendationcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderedScenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_order', models.JSONField(default=list)),
                ('user_level', models.CharField(default='A1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ordered Scenarios',
                'verbose_name_plural': 'User Ordered Scenarios',
                'db_table': 'user_ordered_scenarios',
            },
        ),
        migrations.DeleteModel(
            name='UserRecommendationCache',
        ),
    ]
