# Generated by Django 5.2.7 on 2026-01-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory_palace', '0003_scenario_remove_room_prerequisite_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMilestoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('exercises_completed', models.PositiveIntegerField(default=0)),
                ('exercises_total', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('last_score', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='memory_palace.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('exercise_id', models.PositiveIntegerField()),
                ('user_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts_progress', to=settings.AUTH_USER_MODEL)),
                ('milestone_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to='progress.usermilestoneprogress')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usermilestoneprogress',
            index=models.Index(fields=['user', 'status'], name='progress_us_user_id_1ee4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='usermilestoneprogress',
            index=models.Index(fields=['user', 'milestone'], name='progress_us_user_id_18ea99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermilestoneprogress',
            unique_together={('user', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='userexerciseattempt',
            index=models.Index(fields=['user', 'exercise_type', 'exercise_id'], name='progress_us_user_id_bb609c_idx'),
        ),
        migrations.AddIndex(
            model_name='userexerciseattempt',
            index=models.Index(fields=['user', 'completed_at'], name='progress_us_user_id_76125f_idx'),
        ),
    ]
