# Generated by Django 5.2.7 on 2026-01-14 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory_palace', '0003_scenario_remove_room_prerequisite_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('source_language', models.CharField(default='es', max_length=5)),
                ('target_language', models.CharField(default='en', max_length=5)),
                ('translation', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('frequency_rank', models.PositiveIntegerField(default=0)),
                ('part_of_speech', models.CharField(blank=True, max_length=20)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('audio_url', models.URLField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('is_active_vocab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Vocabulary',
                'ordering': ['frequency_rank', 'word'],
                'indexes': [models.Index(fields=['level', 'target_language'], name='content_voc_level_ba9647_idx'), models.Index(fields=['frequency_rank'], name='content_voc_frequen_5a09d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('learning', 'Aprendiendo'), ('review', 'En repaso'), ('mastered', 'Dominada')], default='new', max_length=20)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('times_incorrect', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.vocabulary')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review'], name='content_use_user_id_db5d9d_idx'), models.Index(fields=['user', 'status'], name='content_use_user_id_aa0300_idx')],
                'unique_together': {('user', 'vocabulary')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=3)),
                ('context_example', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_usages', to='memory_palace.scenario')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='content.vocabulary')),
            ],
            options={
                'unique_together': {('vocabulary', 'scenario')},
            },
        ),
    ]
