# Generated by Django 5.2.7 on 2026-01-14 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('memory_palace', '0003_scenario_remove_room_prerequisite_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=200)),
                ('examples', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('exceptions', models.JSONField(default=list)),
                ('estimated_time', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('examples', models.JSONField(default=list)),
                ('exercises', models.JSONField(default=list)),
                ('estimated_time', models.PositiveIntegerField(default=10)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.grammartopic')),
            ],
            options={
                'ordering': ['topic', 'order'],
                'unique_together': {('topic', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_focus', to='memory_palace.milestone')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.grammartopic')),
            ],
            options={
                'unique_together': {('milestone', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserGrammarProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('mastered', 'Dominado')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('practice_count', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.grammartopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='content_use_user_id_e4d2c2_idx'), models.Index(fields=['user', 'next_review'], name='content_use_user_id_0a5b75_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
