# Generated by Django 5.2.7 on 2026-01-16 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muy difícil')], default=3)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.CharField(blank=True, help_text="Instrucciones para el usuario, ej: 'Ordena las palabras'", max_length=200)),
                ('sentence_with_blanks', models.CharField(help_text='Oración con ___ donde va la respuesta', max_length=300)),
                ('correct_answers', models.JSONField(default=list, help_text="Lista de respuestas correctas, ej: ['am', 'I am']")),
                ('options', models.JSONField(blank=True, default=list, help_text="Opciones para elegir, ej: ['am', 'is', 'are']")),
                ('sentence_complete', models.CharField(blank=True, help_text='Oración completa para mostrar como feedback', max_length=300)),
                ('hint', models.CharField(blank=True, help_text="Pista opcional, ej: '(verbo to be)'", max_length=100)),
                ('translation', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Fill in the Blank Exercise',
                'verbose_name_plural': 'Fill in the Blank Exercises',
            },
        ),
        migrations.CreateModel(
            name='MatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muy difícil')], default=3)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.CharField(blank=True, help_text="Instrucciones para el usuario, ej: 'Ordena las palabras'", max_length=200)),
                ('left_items', models.JSONField(help_text='Items de la columna izquierda')),
                ('right_items', models.JSONField(help_text='Items de la columna derecha')),
                ('correct_pairs', models.JSONField(help_text="Mapeo de índices, ej: {'0': 1, '1': 0, '2': 2}")),
                ('context', models.CharField(blank=True, help_text="Tema del matching, ej: 'Saludos'", max_length=100)),
            ],
            options={
                'verbose_name': 'Matching Exercise',
                'verbose_name_plural': 'Matching Exercises',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muy difícil')], default=3)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.CharField(blank=True, help_text="Instrucciones para el usuario, ej: 'Ordena las palabras'", max_length=200)),
                ('question', models.TextField(help_text='Pregunta o contexto para el ejercicio')),
                ('options', models.JSONField(help_text="Lista de opciones, ej: ['am', 'is', 'are', 'be']")),
                ('correct_indices', models.JSONField(help_text='Índices de opciones correctas, ej: [0] o [0, 2]')),
                ('allow_multiple', models.BooleanField(default=False, help_text='Si true, usuario puede seleccionar múltiples')),
                ('explanation', models.TextField(blank=True, help_text='Explicación de por qué es correcta')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Multiple Choice Exercise',
                'verbose_name_plural': 'Multiple Choice Exercises',
            },
        ),
        migrations.CreateModel(
            name='WordOrderExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muy difícil')], default=3)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.CharField(blank=True, help_text="Instrucciones para el usuario, ej: 'Ordena las palabras'", max_length=200)),
                ('sentence', models.CharField(help_text="Oración correcta, ej: 'I am a teacher'", max_length=300)),
                ('words_shuffled', models.JSONField(default=list, help_text='Lista de palabras desordenadas')),
                ('translation', models.CharField(blank=True, help_text='Traducción al español', max_length=300)),
                ('audio_url', models.URLField(blank=True)),
                ('alternative_answers', models.JSONField(default=list, help_text="Otras respuestas válidas, ej: ['I'm a teacher']")),
            ],
            options={
                'verbose_name': 'Word Order Exercise',
                'verbose_name_plural': 'Word Order Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('exercise_id', models.PositiveIntegerField()),
                ('user_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
