# Generated by Django 5.2.7 on 2026-01-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('grammar', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankexercise',
            name='grammar_unit',
            field=models.ForeignKey(blank=True, help_text='Grammar unit that this exercise practices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exercises', to='grammar.grammarunit'),
        ),
        migrations.AddField(
            model_name='fillblankexercise',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exercises', to='scenarios.milestone'),
        ),
        migrations.AddField(
            model_name='matchingexercise',
            name='grammar_unit',
            field=models.ForeignKey(blank=True, help_text='Grammar unit that this exercise practices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exercises', to='grammar.grammarunit'),
        ),
        migrations.AddField(
            model_name='matchingexercise',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exercises', to='scenarios.milestone'),
        ),
        migrations.AddField(
            model_name='multiplechoiceexercise',
            name='grammar_unit',
            field=models.ForeignKey(blank=True, help_text='Grammar unit that this exercise practices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exercises', to='grammar.grammarunit'),
        ),
        migrations.AddField(
            model_name='multiplechoiceexercise',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exercises', to='scenarios.milestone'),
        ),
        migrations.AddField(
            model_name='wordorderexercise',
            name='grammar_unit',
            field=models.ForeignKey(blank=True, help_text='Grammar unit that this exercise practices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exercises', to='grammar.grammarunit'),
        ),
        migrations.AddField(
            model_name='wordorderexercise',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exercises', to='scenarios.milestone'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'exercise_type', 'exercise_id'], name='exercises_e_user_id_58e538_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'completed_at'], name='exercises_e_user_id_bf6e34_idx'),
        ),
    ]
