# Generated by Django 5.2.7 on 2026-01-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theme', models.CharField(choices=[('forest', 'Forest'), ('city', 'City'), ('ocean', 'Ocean'), ('mountain', 'Mountain'), ('space', 'Space'), ('desert', 'Desert')], default='forest', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_level', models.PositiveIntegerField(default=1)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('background_image', models.URLField(blank=True)),
                ('icon', models.CharField(default='🌍', max_length=10)),
                ('map_layout', models.JSONField(blank=True, default=dict)),
                ('total_xp_available', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.PositiveIntegerField(default=5)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'World',
                'verbose_name_plural': 'Worlds',
                'db_table': 'worlds',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('boss', 'Boss Challenge'), ('bonus', 'Bonus'), ('review', 'Review')], default='standard', max_length=20)),
                ('icon', models.CharField(default='🏠', max_length=10)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='memory_palace.room')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['world', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MemoryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_type', models.CharField(choices=[('lesson', 'Lesson'), ('practice', 'Practice'), ('challenge', 'Challenge'), ('review', 'Review'), ('boss', 'Boss')], default='lesson', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('is_milestone', models.BooleanField(default=False)),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_ids', models.JSONField(blank=True, default=list)),
                ('xp_reward', models.PositiveIntegerField(default=15)),
                ('unlock_reward', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='memory_palace.room')),
            ],
            options={
                'verbose_name': 'Memory Station',
                'verbose_name_plural': 'Memory Stations',
                'db_table': 'memory_stations',
                'ordering': ['room', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserWorldProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_completed', models.JSONField(default=list)),
                ('stations_completed', models.JSONField(default=list)),
                ('world_xp', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='memory_palace.room')),
            ],
            options={
                'verbose_name': 'User World Progress',
                'verbose_name_plural': 'User World Progress',
                'db_table': 'user_world_progress',
            },
        ),
    ]
