# Generated by Django 5.2.7 on 2026-01-13 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory_palace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userworldprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userworldprogress',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='memory_palace.world'),
        ),
        migrations.AddField(
            model_name='room',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='memory_palace.world'),
        ),
        migrations.AlterUniqueTogether(
            name='userworldprogress',
            unique_together={('user', 'world')},
        ),
    ]
