# Generated by Django 5.2.7 on 2026-01-20 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar', '0003_alter_grammarinmilestone_context_example'),
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicativeIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único (ej: introduce-self, order-food)', unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: "Introduce yourself")', max_length=200)),
                ('description', models.TextField(help_text='Descripción CEFR de la intención comunicativa')),
                ('category', models.CharField(choices=[('identity', 'Identity & Personal Info'), ('social', 'Social Interaction'), ('needs', 'Needs & Requests'), ('possession', 'Possession & Existence'), ('location', 'Location & Direction'), ('shopping', 'Shopping'), ('time', 'Time & Routine'), ('ability', 'Ability & Preference'), ('description', 'Description'), ('survival', 'Communication Survival')], help_text='Categoría CEFR del intent', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', help_text='Nivel CEFR', max_length=2)),
                ('cefr_rank', models.IntegerField(default=3, help_text='Ranking de prioridad 1-5 (NO orden absoluto): 1=crítico, 5=opcional')),
                ('is_core', models.BooleanField(default=True, help_text='Si es intent core obligatorio del nivel CEFR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Communicative Intent',
                'verbose_name_plural': 'Communicative Intents',
                'db_table': 'communicative_intent',
                'ordering': ['level', 'cefr_rank', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='IntentGrammarDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True, help_text='Si es crítica (usuario DEBE aprenderla antes) u opcional')),
                ('order', models.IntegerField(default=1, help_text='Orden de enseñanza dentro del intent (1 primero)')),
                ('usage_note', models.TextField(blank=True, help_text='Nota de por qué esta grammar es necesaria para este intent')),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_dependencies', to='grammar.grammarunit')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_dependencies', to='intents.communicativeintent')),
            ],
            options={
                'verbose_name': 'Intent Grammar Dependency',
                'verbose_name_plural': 'Intent Grammar Dependencies',
                'db_table': 'intent_grammar_dependency',
                'ordering': ['intent', 'order'],
                'unique_together': {('intent', 'grammar')},
            },
        ),
        migrations.AddField(
            model_name='communicativeintent',
            name='required_grammar',
            field=models.ManyToManyField(blank=True, help_text='Grammar típicamente necesaria (puede variar por contexto)', related_name='supporting_intents', through='intents.IntentGrammarDependency', to='grammar.grammarunit'),
        ),
        migrations.CreateModel(
            name='IntentRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_chunks', models.JSONField(help_text='Chunks específicos para ESTE contexto: ["Can I have a coffee?", "I\'d like water"]')),
                ('example_chunks_es', models.JSONField(blank=True, default=list, help_text='Chunks en español (opcional, para referencia)')),
                ('difficulty', models.IntegerField(default=1, help_text='Dificultad EN ESTE contexto (1-5)')),
                ('estimated_time', models.IntegerField(default=10, help_text='Tiempo estimado EN ESTE contexto (minutos)')),
                ('priority', models.IntegerField(default=1, help_text='Prioridad dentro de este milestone (1 = más importante)')),
                ('is_primary', models.BooleanField(default=False, help_text='Si este milestone es el PRIMARY para aprender este intent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_grammar', models.ManyToManyField(blank=True, help_text='Grammar adicional necesaria en ESTE contexto específico', to='grammar.grammarunit')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='intents.communicativeintent')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_realizations', to='scenarios.milestone')),
            ],
            options={
                'verbose_name': 'Intent Realization',
                'verbose_name_plural': 'Intent Realizations',
                'db_table': 'intent_realization',
                'ordering': ['milestone', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='UserIntentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked - Missing grammar'), ('ready', 'Ready to practice'), ('practicing', 'Practicing'), ('mastered', 'Mastered')], default='locked', max_length=20)),
                ('grammar_progress', models.JSONField(default=dict, help_text='Estado de cada grammar: {"can-infinitive": "mastered", "articles": "learning"}')),
                ('times_practiced', models.IntegerField(default=0)),
                ('last_score', models.IntegerField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='intents.communicativeintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Intent Progress',
                'verbose_name_plural': 'User Intent Progress',
                'db_table': 'user_intent_progress',
                'ordering': ['user', 'intent__cefr_rank'],
            },
        ),
        migrations.AddIndex(
            model_name='communicativeintent',
            index=models.Index(fields=['level', 'cefr_rank'], name='communicati_level_5a763b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicativeintent',
            index=models.Index(fields=['category'], name='communicati_categor_34ab5b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicativeintent',
            index=models.Index(fields=['is_core'], name='communicati_is_core_41e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='intentrealization',
            index=models.Index(fields=['milestone', 'priority'], name='intent_real_milesto_af6412_idx'),
        ),
        migrations.AddIndex(
            model_name='intentrealization',
            index=models.Index(fields=['intent', 'is_primary'], name='intent_real_intent__26a0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='intentrealization',
            index=models.Index(fields=['difficulty'], name='intent_real_difficu_817bc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intentrealization',
            unique_together={('intent', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='userintentprogress',
            index=models.Index(fields=['user', 'status'], name='user_intent_user_id_917265_idx'),
        ),
        migrations.AddIndex(
            model_name='userintentprogress',
            index=models.Index(fields=['user', 'intent'], name='user_intent_user_id_23e6d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userintentprogress',
            unique_together={('user', 'intent')},
        ),
    ]
