# Generated by Django 5.2.7 on 2026-01-16 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único (ej: can-infinitive, a-an-articles)', unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Can + Infinitive)', max_length=100)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, help_text='Nivel CEFR donde se introduce', max_length=2)),
                ('grammatical_category', models.CharField(choices=[('modal_verb', 'Modal Verbs'), ('article', 'Articles'), ('tense', 'Tenses'), ('pronoun', 'Pronouns'), ('preposition', 'Prepositions'), ('conjunction', 'Conjunctions'), ('question_form', 'Question Formation'), ('negation', 'Negation'), ('auxiliary', 'Auxiliary Verbs'), ('possessive', 'Possessives'), ('comparative', 'Comparatives/Superlatives'), ('gerund_infinitive', 'Gerunds & Infinitives')], help_text='Categoría gramatical', max_length=50)),
                ('form', models.TextField(help_text='Forma gramatical (ej: can + base verb)')),
                ('meaning_en', models.TextField(help_text='Significado/función en inglés (ej: Ability, permission, possibility)')),
                ('meaning_es', models.TextField(help_text='Significado/función en español (ej: Habilidad, permiso, posibilidad)')),
                ('structural_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata estructural de la gramática:\n        {\n          "pattern": "SUBJECT + can + BASE_VERB",\n          "valid_forms": ["I can", "you can", "he can"],\n          "conjugation": {"I": "can", "you": "can", "he/she/it": "can"},\n          "components": {\n            "modal": "can",\n            "verb_form": "base/infinitive"\n          }\n        }')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Ejemplos genéricos (no contextuales): [{"en": "I can swim", "es": "Puedo nadar"}]')),
                ('common_error_patterns', models.JSONField(blank=True, default=list, help_text='Errores comunes y correcciones:\n        [\n          {\n            "error": "He cans swim",\n            "rule": "Modal verbs don\'t add -s in 3rd person",\n            "correction": "He can swim"\n          }\n        ]')),
                ('is_universal', models.BooleanField(default=True, help_text='¿Se usa en todos los contextos? (Siempre True para grammar)')),
                ('pedagogical_sequence', models.PositiveIntegerField(default=1, help_text='Orden GLOBAL de introducción (1=can, 2=will, 3=could, etc.)')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('claude', 'Generated by Claude'), ('imported', 'Imported from dataset')], default='manual', help_text='Origen de los datos', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grammar Unit',
                'verbose_name_plural': 'Grammar Units',
                'db_table': 'grammar_unit',
                'ordering': ['pedagogical_sequence', 'level'],
                'indexes': [models.Index(fields=['level', 'grammatical_category'], name='grammar_uni_level_af44e6_idx'), models.Index(fields=['pedagogical_sequence'], name='grammar_uni_pedagog_e1687e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrammarInMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_example', models.TextField(blank=True, help_text='Ejemplo en contexto específico (ej: Can I have a coffee?)')),
                ('importance_weight', models.IntegerField(choices=[(1, 'Opcional'), (2, 'Útil'), (3, 'Importante'), (4, 'Muy importante'), (5, 'Crítico')], default=3, help_text='Importancia de este grammar en este milestone')),
                ('is_primary_focus', models.BooleanField(default=False, help_text='¿Este grammar es el OBJETIVO principal del milestone?')),
                ('introduction_order', models.PositiveIntegerField(default=1, help_text='Orden de introducción EN ESTE MILESTONE (grammar antes que vocabulario)')),
                ('suggested_vocabulary_words', models.JSONField(blank=True, default=list, help_text='Palabras que se combinan bien con este grammar en este contexto: ["coffee", "water", "menu"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(help_text='Milestone donde se usa este grammar', on_delete=django.db.models.deletion.CASCADE, related_name='grammar_items', to='scenarios.milestone')),
                ('grammar', models.ForeignKey(help_text='Grammar unit universal', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_usages', to='grammar.grammarunit')),
            ],
            options={
                'verbose_name': 'Grammar in Milestone',
                'verbose_name_plural': 'Grammar in Milestones',
                'db_table': 'grammar_in_milestone',
                'ordering': ['introduction_order'],
                'indexes': [models.Index(fields=['milestone', 'importance_weight'], name='grammar_in__milesto_9741c8_idx'), models.Index(fields=['milestone', 'introduction_order'], name='grammar_in__milesto_6ba120_idx')],
                'unique_together': {('grammar', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='UserGrammarProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('learning', 'Aprendiendo'), ('review', 'En repaso'), ('mastered', 'Dominada')], default='new', max_length=20)),
                ('ease_factor', models.FloatField(default=2.5, help_text='Factor de facilidad (SM-2 algorithm)')),
                ('interval', models.PositiveIntegerField(default=1, help_text='Intervalo en días hasta próximo repaso')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='Número de repeticiones correctas consecutivas')),
                ('next_review', models.DateField(default=django.utils.timezone.now, help_text='Fecha del próximo repaso')),
                ('last_reviewed', models.DateTimeField(blank=True, help_text='Última vez que se repasó', null=True)),
                ('times_correct', models.PositiveIntegerField(default=0, help_text='Veces que respondió correctamente')),
                ('times_incorrect', models.PositiveIntegerField(default=0, help_text='Veces que respondió incorrectamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='grammar.grammarunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Grammar Progress',
                'verbose_name_plural': 'User Grammar Progress',
                'db_table': 'user_grammar_progress',
                'ordering': ['next_review', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_gramma_user_id_c5a850_idx'), models.Index(fields=['user', 'next_review'], name='user_gramma_user_id_aab8df_idx'), models.Index(fields=['grammar', 'status'], name='user_gramma_grammar_33944f_idx')],
                'unique_together': {('user', 'grammar')},
            },
        ),
    ]
