# Generated by Django 5.2.7 on 2026-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarunit',
            options={'ordering': ['target_language', 'pedagogical_sequence', 'level'], 'verbose_name': 'Grammar Unit', 'verbose_name_plural': 'Grammar Units'},
        ),
        migrations.AddField(
            model_name='grammarunit',
            name='target_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German / Deutsch'), ('fr', 'French / Français')], db_index=True, default='en', help_text='Idioma objetivo que este grammar unit enseña (ISO 639-1 code)', max_length=5),
        ),
        migrations.AlterField(
            model_name='grammarunit',
            name='grammatical_category',
            field=models.CharField(choices=[('modal_verb', 'Modal Verbs'), ('article', 'Articles'), ('tense', 'Tenses'), ('pronoun', 'Pronouns'), ('preposition', 'Prepositions'), ('conjunction', 'Conjunctions'), ('question_form', 'Question Formation'), ('negation', 'Negation'), ('auxiliary', 'Auxiliary Verbs'), ('possessive', 'Possessives'), ('comparative', 'Comparatives/Superlatives'), ('gerund_infinitive', 'Gerunds & Infinitives'), ('adverb', 'Adverbs'), ('adjective', 'Adjectives'), ('verb', 'Verbs'), ('gender', 'Grammatical Gender'), ('case_system', 'Case System'), ('declension', 'Declension'), ('verb_mood', 'Verb Moods'), ('adjective_agreement', 'Adjective Agreement'), ('word_order', 'Word Order')], help_text='Categoría gramatical', max_length=50),
        ),
        migrations.AlterField(
            model_name='grammarunit',
            name='slug',
            field=models.SlugField(help_text='Identificador único (ej: can-infinitive, a-an-articles, verbe-etre, artikel-der-die-das)'),
        ),
        migrations.AlterUniqueTogether(
            name='grammarunit',
            unique_together={('slug', 'target_language')},
        ),
        migrations.AddIndex(
            model_name='grammarunit',
            index=models.Index(fields=['target_language', 'level'], name='grammar_uni_target__9666f7_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarunit',
            index=models.Index(fields=['target_language', 'grammatical_category'], name='grammar_uni_target__e96ab6_idx'),
        ),
    ]
