# Generated by Django 5.2.7 on 2026-01-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_alter_grammarunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarinmilestone',
            name='context_example',
            field=models.JSONField(blank=True, default=list, help_text='Ejemplos: ["Example 1", "Example 2"]'),
        ),
    ]
