# Generated by Django 5.2.10 on 2026-01-13 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('step_type', models.CharField(choices=[('welcome', 'Welcome'), ('language_select', 'Language Selection'), ('goal_select', 'Goal Setting'), ('level_select', 'Level Selection'), ('style_assessment', 'Learning Style Assessment'), ('time_commitment', 'Time Commitment'), ('avatar_create', 'Avatar Creation'), ('world_preview', 'World Preview'), ('first_lesson', 'First Lesson')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('component_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('is_skippable', models.BooleanField(default=False)),
                ('icon', models.CharField(default='📝', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Onboarding Step',
                'verbose_name_plural': 'Onboarding Steps',
                'db_table': 'onboarding_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VAKAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('visual_option', models.CharField(max_length=255)),
                ('auditory_option', models.CharField(max_length=255)),
                ('kinesthetic_option', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VAK Assessment Question',
                'verbose_name_plural': 'VAK Assessment Questions',
                'db_table': 'vak_assessment_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('completed_steps', models.JSONField(default=list)),
                ('collected_data', models.JSONField(default=dict)),
                ('vak_answers', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Onboarding Progress',
                'verbose_name_plural': 'User Onboarding Progress',
                'db_table': 'user_onboarding_progress',
            },
        ),
    ]
